accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug>', views.article_detail, name='detail'),
]

bmi/urls.py
from django.urls import path
from . import views

app_name = 'bmi'

urlpatterns = [
    path('', views.bmi, name='bmi'),
]

djangonautic/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name='home'),
    path('accounts/', include('accounts.urls')),
    path('weather/', include('weather.urls')),
    path('bmi/', include('bmi.urls')),
    path('medinfo/', include('medinfo.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather_view, name='weather'),

]

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About Us</h1>
        <p>We like django.</p>
    </body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'bmi.css' %}">
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

    </head>
    <body>
        <div class="wrapper">
            <header>
            <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li class="highlight">
                        <a href="{% url 'articles:create' %}">Create Article</a>
                    </li>
                    <li class="bmi-link">
                        <a href="{% url 'bmi:bmi' %}">
                            <button>BMI Calculator</button>
                        </a>
                    </li>
                    {% else %}
                    
                    <li class="login-link">
                        <a href="{% url 'accounts:login' %}">
                            <button>Login</button>
                        </a>
                    </li>
                    <li class="signup-link">
                        <a href="{% url 'accounts:signup' %}">
                            <button>Signup</button>
                        </a>
                    </li>
                    <li class="weather-link">
                        <a href="{% url 'weather:weather' %}">
                            <button>Weather</button>
                        </a>
                    </li>
                    <li class="bmi-link">
                        <a href="{% url 'bmi:bmi' %}">
                            <button>BMI Calculator</button>
                        </a>
                    </li>
                    {% endif %}
                    
                </ul>
            </nav>
            </header>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Djangonauts</p>
    </body>
</html>